# This file was automatically generated by Znake
try:
    import fastentrypoints
except ImportError as e:
    pass
from setuptools import setup, find_packages

try:
    from pycred.version import (
        __version__,
        deb_package_name,
        description,
        long_description,
        maintainer,
        maintainer_email)
except ImportError:
    __version__ = '0.0.0'
    deb_package_name = 'unknown'
    description = 'unknown'
    long_description = 'unknown'
    maintainer = 'unknown'
    maintainer_email = 'unknown'

setup(
    name=deb_package_name,
    version=__version__,

    description=description,
    long_description=long_description,

    maintainer=maintainer,
    maintainer_email=maintainer_email,

    license='© 2018 DevConSoft All rights reserved, or under MIT license',

    classifiers=[
        'Development Status :: 3 - Alpha',
        'Intended Audience :: Developers',
        'License :: MIT',
        'Programming Language :: Python :: 3.4',
        'Programming Language :: Python :: 3.5',
        'Programming Language :: Python :: 3.6',
    ],

    keywords='',

    packages=find_packages(exclude=['*.test', '*.test.*', 'test.*', 'systest', 'systest.*', 'example', 'example.*', ]),

    install_requires=[
        'click',
        'coloredlogs',
        'ruamel.yaml',
        'py',
    ],

    entry_points={
        'console_scripts': [
            'pycred = pycred.ui.__main__:main',
        ],
    },

    

    package_data={
        'pycred': ['pycred/.config.yaml'],
    },

)