---
!PyCredConfig
encryptions: !PyCredBackendDefaultConfig
  default: 'clear'
  backends:
  - !BackendConfig
    data: {}
    name: 'clear'
serializers: !PyCredBackendDefaultConfig
  default: 'json'
  backends:
  - !BackendConfig
    data: {}
    name: 'json'
storages: !PyCredBackendDefaultConfig
  backends:
  - !BackendConfig
    data:
      data_dir: '~/.pycred/data/%store%/storage/file'
    name: 'file'
  - !BackendConfig
    data: {}
    name: 'memory'
  default: 'file'
store_path: '~/.pycred/store'
