# This file is automatically generated by Znake
from textwrap import dedent

__version__ = '0.0.1+0'
__updated__ = '2018-07-10'
deb_package_name = 'pycred'
description = 'Store user credentials'
long_description = dedent('''\\
    PyCred is an application and python3 library that allow storing and retrieving
    user credentials for multiple systems.
    ''')
maintainer = 'Per Böhlin'
maintainer_email = 'per.bohlin@devconsoft.se'

changelog = [
    {
        'version': '0.0.1',
        'date': 'Fri, 22 Jun 2018 12:00:00 +0000',
        'changes': [
            'First draft',
        ],
    },
]
